### ISSUE TITLE
Linki do faktury 

### ISSUE THREAD

**Issue by Viperoo** [ifirma/ifirma-api-sklepy#7]
Witam,

Wie ktoś jak wygenerować link do faktury który ma teraz format 

```
https://www.ifirma.pl/app/wo/77.0.0.1.23.11.5.5.3.1.7.1.1.3.1.4.1.1.0.1.3.3.1.3.1.1 
```
Czy raczej nie da rady bo sesja itp?

Pozdrawiam

**Comment by konradkg** [comment]
Nie, tak się nie da ;)
Napisz proszę, co chcesz osiągnąć, to podpowiem ewentualnie jak to zrobic :) 

Zgadując:
Jeżeli chcesz wysłać link do faktury mailem, to musisz:
1) pobrać przez api fakture i trzymac u siebie, i podac link do lpiku na twojej stronie
2) napisac skrypt, który na podstawie parametrów pobierze z api ifirmy fakturę i zwróci ją w odpowiedzi.

**Comment by Viperoo** [comment]
Dzięki za odpowiedź :)

Chcę w zewnętrznej aplikacji zrobić link do podglądu faktury w ifirmie ponieważ nie implementuję na tą chwilę wszystkich funkcjonalności takich jak np. zapisywanie z proformy do faktury. 

Czyli np. mam sobie listę faktur i tam link do _pokaż w ifirma_.

Ale jak się nie da to trudno, będzie trzeba ręcznie sobie wyszukiwać fakturkę.

Pozdrawiam

**Comment by konradkg** [comment]
zapisanie faktury z proformy, sprowadza się do wywołania metodą GET:
`https://www.ifirma.pl/iapi/fakturaproformakraj/add/[NUMER_LUB_ID_PROFORMY].json`
a pobranie potem tej faktury w PDF: 
`https://www.ifirma.pl/iapi/fakturakraj/[NUMER_LUB_ID_FAKTURY].pdf.single`
